title: freifunk GSoC Projects
license: GNU AFFERO GENERAL PUBLIC LICENSE V3.0
organization: freifunk.net
description: A website that showcases interesting projects, using Angular JS.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://projects.freifunk.net"  # the base hostname & protocol for your site

plugins:
  - jekyll-netlify

# Build settings
exclude: [vendor]
markdown: kramdown
collections:
  projects:
    output: true
  faq:
    output: true
